// blockConfig.js
// Central config for all block types, theme variants, and their default content.
// Every other file imports from here — don't hardcode block types anywhere else.

// ─── Theme definitions ────────────────────────────────────────────────────────
// Each theme only defines colors. Font sizes, spacing, borders come from base CSS.

export const THEMES = {
  dark: {
    label: 'Dark',
    styles: {
      background: '#0f172a',
      color: '#f8fafc',
      accentColor: '#38bdf8',
      borderColor: '#1e293b',
    },
  },
  minimal: {
    label: 'Minimal',
    styles: {
      background: '#ffffff',
      color: '#1e293b',
      accentColor: '#000000',
      borderColor: '#e2e8f0',
    },
  },
  light: {
    label: 'Light',
    styles: {
      background: '#f8fafc',
      color: '#334155',
      accentColor: '#2563eb',
      borderColor: '#e2e8f0',
    },
  },
};

// ─── Block definitions ────────────────────────────────────────────────────────
// Each block has:
//   type        — unique key, used to pick the right component and template
//   label       — display name shown in the library
//   defaultContent — the shape of content when a new block is added
//   elements    — the editable fields inside the block (drives BlockEditor UI)

export const BLOCK_DEFINITIONS = [
  {
    type: 'about',
    label: 'About Me',
    defaultContent: {
      heading: 'About Me',
      subheading: 'Who I am',
      bio: 'Write a short introduction about yourself...',
    },
    elements: [
      { key: 'heading',           label: 'Heading',              inputType: 'text' },
      { key: 'subheading',        label: 'Subheading',           inputType: 'text' },
      { key: 'bio',               label: 'Bio',                  inputType: 'textarea' },
    ],
  },
  {
    type: 'skills',
    label: 'Skills',
    defaultContent: {
      heading: 'Skills',
      subheading: 'What I work with',
      items: ['React', 'Node.js', 'MongoDB'],
    },
    elements: [
      { key: 'heading',           label: 'Heading',              inputType: 'text' },
      { key: 'subheading',        label: 'Subheading',           inputType: 'text' },
      { key: 'items',             label: 'Skills (one per line)',inputType: 'list' },
    ],
  },
  {
    type: 'projects',
    label: 'Projects',
    defaultContent: {
      heading: 'Projects',
      subheading: 'Things I have built',
      items: [
        { name: 'Project Name', description: 'What this project does...', link: '' },
      ],
    },
    elements: [
      { key: 'heading',           label: 'Heading',              inputType: 'text' },
      { key: 'subheading',        label: 'Subheading',           inputType: 'text' },
      { key: 'items',             label: 'Projects',             inputType: 'projects' },
    ],
  },
  {
    type: 'contact',
    label: 'Contact',
    defaultContent: {
      heading: 'Get In Touch',
      subheading: 'I would love to hear from you',
      email: '',
      github: '',
      linkedin: '',
    },
    elements: [
      { key: 'heading',           label: 'Heading',              inputType: 'text' },
      { key: 'subheading',        label: 'Subheading',           inputType: 'text' },
      { key: 'email',             label: 'Email',                inputType: 'text' },
      { key: 'github',            label: 'GitHub URL',           inputType: 'text' },
      { key: 'linkedin',          label: 'LinkedIn URL',         inputType: 'text' },
    ],
  },
];

// ─── Helper: get definition by type ──────────────────────────────────────────
export const getBlockDefinition = (type) =>
  BLOCK_DEFINITIONS.find((b) => b.type === type);

// ─── Helper: build a fresh block object ──────────────────────────────────────
// Called when user drags a card from the library onto the canvas.
// id is generated by the caller (use crypto.randomUUID() or Date.now()).
export const createBlock = (type, theme, id) => {
  const definition = getBlockDefinition(type);
  if (!definition) throw new Error(`Unknown block type: ${type}`);
  return {
    id,
    type,
    theme,                                      // 'dark' | 'minimal' | 'light'
    order: 0,                                   // Canvas sets the real order on drop
    content: { ...definition.defaultContent },  // shallow copy of defaults
  };
};